version: '3.8'
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes: 
      - ./:/app
    container_name: minecraft
    command: sh -c 'cd /app; echo "eula=true" > eula.txt; dos2unix start-server.sh; chmod +x start-server.sh; ./start-server.sh'
    stdin_open: true
    tty: true